// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Op9yA1Gxs1FhyTIQsuAXtt0ZZHbqQbM',
    appId: '1:674879567065:web:8d5637ec71a83128aebac8',
    messagingSenderId: '674879567065',
    projectId: 'test-todo-3b6dd',
    authDomain: 'test-todo-3b6dd.firebaseapp.com',
    storageBucket: 'test-todo-3b6dd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2JsN-DJE07itL0RchpekReIlSUF1QsXE',
    appId: '1:674879567065:android:1e1de8e2d7acbb8daebac8',
    messagingSenderId: '674879567065',
    projectId: 'test-todo-3b6dd',
    storageBucket: 'test-todo-3b6dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6iEh5br1g2VJy0ntGV8l8IFvzBpuRj8o',
    appId: '1:674879567065:ios:32147ebe15816780aebac8',
    messagingSenderId: '674879567065',
    projectId: 'test-todo-3b6dd',
    storageBucket: 'test-todo-3b6dd.appspot.com',
    iosBundleId: 'com.example.newsipify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6iEh5br1g2VJy0ntGV8l8IFvzBpuRj8o',
    appId: '1:674879567065:ios:0011c7f35d24c97faebac8',
    messagingSenderId: '674879567065',
    projectId: 'test-todo-3b6dd',
    storageBucket: 'test-todo-3b6dd.appspot.com',
    iosBundleId: 'com.example.newsipify.RunnerTests',
  );
}
